### PR TITLE
III-5024 change facility

### PR DESCRIPTION
**Pull request by JonasVHG**
### Added

- `Low incentive` category
- `Agreements and predictability` category

### Removed

- `Feel chairs`  category
- `Free carer ticket` category

---

Ticket: https://jira.uitdatabank.be/browse/III-5024

### CODE REVIEW

**Comment by willaerk** [comment]
Enige dat ik zie dat misschien niet optimaal is, is dat "Publiq" als creator met een hoofdletter start. Maar dat is op andere plaatsen in die file ook. Geen idee of we dat beter fiksen.

**Comment by JonasVHG** [comment]
> Enige dat ik zie dat misschien niet optimaal is, is dat "Publiq" als creator met een hoofdletter start. Maar dat is op andere plaatsen in die file ook. Geen idee of we dat beter fiksen.

@corneelwille do you have a preference for `publiq` or `Publiq`? But since the creator is only shown in the legacy xml and most of them are still `CultuurNet` I wouldn't really bother with changing some or all of them.

**Comment by corneelwille** [comment]
> > Enige dat ik zie dat misschien niet optimaal is, is dat "Publiq" als creator met een hoofdletter start. Maar dat is op andere plaatsen in die file ook. Geen idee of we dat beter fiksen.
> 
> @corneelwille do you have a preference for `publiq` or `Publiq`? But since the creator is only shown in the legacy xml and most of them are still `CultuurNet` I wouldn't really bother with changing some or all of them.

Minor issue ofc but `publiq` (lowercase) is the only correct notation so I suggest to replace `CultuurNet` and `Publiq` with `publiq`.

**Review by corneelwille — APPROVED** [review]

**Comment by JonasVHG** [comment]
> 
> Minor issue ofc but `publiq` (lowercase) is the only correct notation so I suggest to replace `CultuurNet` and `Publiq` with `publiq`.

I'll make a seperate PR(https://jira.uitdatabank.be/browse/III-5061) for that since it would update +20 files and is out of scope of just the facilities ticket

**Review by willaerk — APPROVED** [review]

**Comment by bertramakers** [comment]
> But since the creator is only shown in the legacy xml and most of them are still CultuurNet I wouldn't really bother with changing some or all of them.

I agree that since it's legacy XML we are probably better of leaving it like it is, since we don't know who uses this (maybe someone filters by the `createdby="CultuurNet"`?), and it's irrelevant for the new JSON API.

**Pull request merged**
